Description: Template for creating EC2 instance

Parameters:
  InstanceType:
    Description: EC2 instance config
    Type: String
    Default: t2.micro

  ImageId:
    Description: EC2 instance image config
    Type: String
    Default: ami-00dfe2c7ce89a450b

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: id_rsa_aws.pub
      ImageId: !Ref ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Description: SSH Security Group for accessing EC2 instance
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  PublicIp:
    Description: EC2 public IP
    Value: !GetAtt EC2Instance.PublicIp
